### ISSUE TITLE
[BUG] {PLOVER:end_solo_dict} and {PLOVER:solo_dict} do not work at all

### ISSUE THREAD

**Issue by Monniasza** [KoiOates/plover_dict_commands#3]
Hi. I've tried to set up your plugin as described in https://joshuagrams.github.io/steno-jig/raw-steno-instructions.html, but the plugin throws a KeyError every time I try to use it.
I've used `RA*U` for {PLOVER:solo_dict} and `RAU*R` for {PLOVER:end_solo_dict}.
![image](https://github.com/KoiOates/plover_dict_commands/assets/37037712/07e775f0-15d0-4cb6-9d44-71b047f0ae68)
![image](https://github.com/KoiOates/plover_dict_commands/assets/37037712/b02402d8-3264-496f-9d46-d97c551adefb)

**Comment by Monniasza** [comment]
Additionally, toggle dictionary does not work either

**Comment by benoit-pierre** [comment]
Did you restart Plover after installing the plugin?

**Comment by Monniasza** [comment]
It now works after restarting
